import { useState, useEffect } from 'react';
import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';

import { MantineProvider } from '@mantine/core';
import { Title, Text } from '@mantine/core';

import {
  fetchConditionCounts,
  type ConditionCountsResponse,
} from './services/syntheaApiService';

export default function App() {
  const [conditionCounts, setConditionCounts] = useState<
    ConditionCountsResponse[] | null
  >(null);

  const baseUrl = 'http://localhost:8080';

  useEffect(() => {
    const fetchData = async () => {
      const data = await fetchConditionCounts(baseUrl);

      if (data) {
        setConditionCounts(data);
      } else {
        console.warn('No condition counts data received from the API.');
      }
    };

    fetchData();
  }, []);

  console.log('conditionCounts:', conditionCounts);

  return (
    <MantineProvider>
      <div>
        <Title>Synthea patient insights</Title>
        <Text>
          A small dashboard exploring sythetic patient data generated by Synthea
        </Text>
        <Title order={2} mt="md">
          Top conditions by gender
        </Title>
        <Text>
          The most frequently recorded conditions, broken down by patient gender
        </Text>
      </div>
    </MantineProvider>
  );
}
