import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';

import { MantineProvider } from '@mantine/core';
import { Title, Text, Container, Stack } from '@mantine/core';

import ConditionsCountChartCard from './components/ConditionsCountChartCard';

export default function App() {
  return (
    <MantineProvider>
      <Container my="xl">
        <Stack justify="center" align="center" mb="xl">
          <Title>Synthea patient insights</Title>
          <Text>
            A small dashboard exploring sythetic patient data generated by
            Synthea
          </Text>
        </Stack>

        <ConditionsCountChartCard />
      </Container>
    </MantineProvider>
  );
}
